class CreatePushSubscriptions < ActiveRecord::Migration[8.1]
  # One row per browser (strictly: per service worker registration) that has
  # been granted notification permission and subscribed. A single user has as
  # many as they have devices and browsers, which is why this is a table
  # rather than columns on profiles.
  #
  # The three fields the Web Push protocol needs are the endpoint (a URL at
  # the browser vendor's push service) and the two keys the payload is
  # encrypted against. Nothing here is a Rally secret — p256dh is the
  # subscriber's public key and auth is a shared secret generated by the
  # browser for this subscription — but they're per-user data and only ever
  # travel between us and the push service, never back to the client.
  def change
    create_table :push_subscriptions, id: :uuid, default: -> { "gen_random_uuid()" } do |t|
      t.references :user, null: false, foreign_key: true, type: :uuid, index: false

      # The natural key. A browser hands back the same endpoint if you
      # subscribe twice with the same VAPID key, so uniqueness here is what
      # makes re-subscribing idempotent instead of accumulating duplicates
      # that would each deliver the same notification.
      #
      # Deliberately :text, not :string — these are long, opaque, vendor-
      # controlled URLs with no documented length limit, and a silent 255-char
      # truncation would corrupt them into undeliverable garbage.
      t.text :endpoint, null: false

      t.string :p256dh_key, null: false
      t.string :auth_key, null: false

      # Purely diagnostic: which browser/device this came from, so a user
      # looking at a list of their subscriptions can tell them apart. Never
      # parsed or branched on.
      t.string :user_agent

      # Set when the push service tells us the subscription is dead (404/410).
      # Kept rather than deleted so a device that goes quiet is visible when
      # debugging "why did I stop getting notifications", instead of just
      # vanishing.
      t.datetime :expired_at

      t.datetime :last_delivered_at

      t.timestamps
    end

    add_index :push_subscriptions, :endpoint, unique: true
    add_index :push_subscriptions, [ :user_id, :expired_at ]
  end
end
