class AddEmailAutoGeneratedToUsers < ActiveRecord::Migration[8.1]
  def change
    # true for an account Registrations::GuestCheckout created for a
    # phone-only guest (email column holds a "guest-...@guest.rally.invalid"
    # placeholder — see that service). Lets the frontend show a "add your
    # real email" nudge instead of the placeholder, and lets
    # RegistrationsController#create skip sending RegistrationMailer
    # confirmation to an address nobody can read.
    add_column :users, :email_auto_generated, :boolean, default: false, null: false
  end
end
