# frozen_string_literal: true

module Conversations
  # Adds a message to a conversation, from either side.
  #
  # Shared by the participant endpoint (Ticket B) and the staff endpoint
  # (Ticket C) rather than duplicated, because everything around the insert —
  # which way the status flips, whose read stamp moves — is symmetric, and two
  # copies would drift the moment one side grew a feature.
  #
  # This is also the single place Ticket D's broadcast and Ticket G's
  # notification will hook into. Keeping it a service now means neither of
  # those has to touch a controller.
  module PostMessage
    module_function

    # `sender_role` is left to the model to derive (position in the thread, not
    # the admin flag — see Message#assign_sender_role). Callers pass a sender,
    # not a role, so there is no way for a controller to mislabel one.
    #
    # Row-locked: two people typing at once would otherwise interleave their
    # status flips, and the thread could settle on "pending" after the
    # participant's message rather than the staff one — quietly dropping it out
    # of the inbox's "awaiting staff" filter.
    def call(conversation:, sender:, body:)
      message = nil

      conversation.with_lock do
        message = conversation.messages.create!(sender: sender, body: body)

        changes = status_change(conversation, message).merge(read_stamp(conversation, message))
        conversation.update!(changes) if changes.any?
      end

      # Safe to call here even though `with_lock` has already committed, and
      # safe if a caller wrapped this whole thing in their own transaction:
      # Broadcast defers to the outermost commit and never fires on rollback.
      Broadcast.message_created(message)

      message
    end

    # A reply from one side is a question for the other:
    #
    #   participant writes -> "open"    (we owe them an answer)
    #   staff writes       -> "pending" (they owe us one)
    #
    # A resolved thread is deliberately left resolved. Reopening on a new
    # message sounds helpful, but it would collide with the one-live-thread
    # index the moment the participant has already started a fresh
    # conversation — and a resolved thread can only receive a message from
    # staff adding a postscript, since the participant endpoint won't write to
    # one.
    def status_change(conversation, message)
      return {} if conversation.resolved?

      next_status = message.from_participant? ? ::Conversation::OPEN : ::Conversation::PENDING
      return {} if conversation.status == next_status

      { status: next_status }
    end

    # You have, by definition, read everything up to the message you just sent.
    # Without this the sender's own reply leaves their own side showing
    # unread — which for staff means a thread they just answered sitting in the
    # "awaiting staff" inbox forever.
    # Monotonic: a read stamp must never move backwards, or messages the reader
    # has already seen silently become unread again.
    #
    # `message.created_at` is generated by the app server, not the database, so
    # it is not guaranteed to be later than a stamp written moments ago by a
    # different ECS task with a slightly different clock. A backfill or import
    # writing historical rows would regress it much more dramatically. Taking
    # the max costs nothing and removes the whole class of problem.
    def read_stamp(conversation, message)
      column = message.from_participant? ? :participant_last_read_at : :staff_last_read_at
      { column => [ conversation.public_send(column), message.created_at ].compact.max }
    end
  end
end
