# ── Passwords / keys generated by Terraform ───────────────────────────────────

resource "random_password" "db_password" {
  length  = 32
  special = false # avoid characters that need URL-encoding in DATABASE_URL
}

resource "random_password" "jwt_secret" {
  length  = 64
  special = false
}

# ── DATABASE_URL ──────────────────────────────────────────────────────────────

resource "aws_secretsmanager_secret" "database_url" {
  name                    = "${local.prefix}/database-url"
  description             = "Rails DATABASE_URL for the production RDS instance"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id = aws_secretsmanager_secret.database_url.id

  # Uses aws_db_instance.main (defined in database.tf) — Terraform handles ordering.
  # postgresql://user:pass@host:5432/dbname
  secret_string = "postgresql://${var.db_username}:${random_password.db_password.result}@${aws_db_instance.main.address}:5432/${var.db_name}"

  depends_on = [aws_db_instance.main]
}

# ── JWT_SECRET ────────────────────────────────────────────────────────────────

resource "aws_secretsmanager_secret" "jwt_secret" {
  name                    = "${local.prefix}/jwt-secret"
  description             = "Secret used to sign and verify JWT tokens"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "jwt_secret" {
  secret_id     = aws_secretsmanager_secret.jwt_secret.id
  secret_string = local.effective_jwt_secret
}

# ── RAILS_MASTER_KEY ──────────────────────────────────────────────────────────

resource "aws_secretsmanager_secret" "rails_master_key" {
  name                    = "${local.prefix}/rails-master-key"
  description             = "Rails master key (config/master.key)"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "rails_master_key" {
  secret_id     = aws_secretsmanager_secret.rails_master_key.id
  secret_string = var.rails_master_key
}

# ── ABA_PAYWAY_MERCHANT_ID / ABA_PAYWAY_API_KEY ────────────────────────────────
# Third-party payment gateway credentials — not AWS-native, so unlike SES
# there's no IAM-role shortcut here. Get these from ABA Bank (see
# ABA_PAYWAY_SETUP.md) and set aba_payway_merchant_id / aba_payway_api_key in
# terraform.tfvars.

resource "aws_secretsmanager_secret" "aba_payway_merchant_id" {
  name                    = "${local.prefix}/aba-payway-merchant-id"
  description             = "ABA PayWay merchant ID"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "aba_payway_merchant_id" {
  secret_id     = aws_secretsmanager_secret.aba_payway_merchant_id.id
  secret_string = var.aba_payway_merchant_id
}

resource "aws_secretsmanager_secret" "aba_payway_api_key" {
  name                    = "${local.prefix}/aba-payway-api-key"
  description             = "ABA PayWay API key (used for HMAC request signing)"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "aba_payway_api_key" {
  secret_id     = aws_secretsmanager_secret.aba_payway_api_key.id
  secret_string = var.aba_payway_api_key
}
