# ── S3 bucket for Active Storage uploads ─────────────────────────────────────
# Private bucket; access is granted to ECS tasks via the task IAM role.
# Files are served via pre-signed URLs generated by the Rails app.

resource "aws_s3_bucket" "uploads" {
  bucket = "${local.prefix}-uploads-${data.aws_caller_identity.current.account_id}"

  tags = { Name = "${local.prefix}-uploads" }
}

resource "aws_s3_bucket_public_access_block" "uploads" {
  bucket = aws_s3_bucket.uploads.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "uploads" {
  bucket = aws_s3_bucket.uploads.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "uploads" {
  bucket = aws_s3_bucket.uploads.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# CORS — required for direct browser uploads via presigned URLs
resource "aws_s3_bucket_cors_configuration" "uploads" {
  bucket = aws_s3_bucket.uploads.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "PUT", "POST", "DELETE", "HEAD"]
    allowed_origins = [
      local.custom_frontend_domain
        ? "https://${var.frontend_domain}"
        : "https://${aws_cloudfront_distribution.frontend.domain_name}",
      "http://localhost:5173", # Vite dev server
      "http://localhost:4173", # Vite preview
    ]
    expose_headers  = ["ETag"]
    max_age_seconds = 3600
  }
}

# Lifecycle: move old uploads to cheaper storage after 90 days
resource "aws_s3_bucket_lifecycle_configuration" "uploads" {
  bucket = aws_s3_bucket.uploads.id

  rule {
    id     = "transition-old-uploads"
    status = "Enabled"

    transition {
      days          = 90
      storage_class = "STANDARD_IA"
    }

    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }
}
