name: CI
permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
  jest:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Jest tests
        run: npm test --ci --coverage --passWithNoTests
        working-directory: ./frontend

  scan_ruby:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: backend

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  scan_js:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: backend

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  rubocop:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: backend

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  Rspec:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          working-directory: backend

      - name: Set up database
        run: |
          sudo apt-get install -y libpq-dev
          bundle exec rails db:create db:schema:load db:seed

      - name: Run RSpec tests
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: |
          bundle exec rspec
